# Generated by Django 4.1.7 on 2023-04-01 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=250, null=True, verbose_name='URL')),
                ('Title', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('Price', models.CharField(max_length=250, null=True, verbose_name='Price')),
                ('Description', models.CharField(max_length=400, null=True, verbose_name='Description')),
                ('DescriptionDetail', models.CharField(max_length=800, null=True, verbose_name='Description Detail')),
                ('Category', models.CharField(max_length=250, null=True, verbose_name='Category')),
                ('Quanity', models.IntegerField(null=True, verbose_name='Quanity')),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
        ),
    ]
