# Generated by Django 4.1.7 on 2023-04-04 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200, null=True, verbose_name='Code')),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
        ),
    ]
