# Generated by Django 4.1.7 on 2023-04-04 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_registrationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWhiteList',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationCode',
        ),
    ]
