# Generated by Django 4.1.7 on 2023-04-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_emailwhitelist_delete_registrationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailwhitelist',
            name='Description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
    ]
