# Generated by Django 4.1.7 on 2023-04-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_emailwhitelist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=450, null=True, verbose_name='Description'),
        ),
    ]
