# Generated by Django 4.1.7 on 2023-04-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
